default_language_version:
  python: python3.10

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: weekly
  # mypy exceeds free tier 250MiB limit on pre-commit.ci
  # https://github.com/pre-commit-ci/issues/issues/171
  skip: [mypy]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        name: No commits to master
      - id: end-of-file-fixer
        name: End-of-file fixer
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: check-toml
        name: Check toml
      - id: check-yaml
        name: Check yaml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: Lint yaml
        args: [-d, '{extends: default, rules: {line-length: disable, document-start: disable, truthy: {level: error}, braces: {max-spaces-inside: 1}}}']

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Remove unused imports and variables
        args: [
          --remove-all-unused-imports,
          --remove-unused-variables,
          --remove-duplicate-keys,
          --ignore-init-module-imports,
          --in-place,
        ]

  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        name: Format code
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Check PEP8
        additional_dependencies: [Flake8-pyproject]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        name: Ruff formatting
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        name: Check types
        additional_dependencies: [torch==2.9.*]
        exclude: "^test/|^examples/|^benchmark/"

  - repo: https://github.com/executablebooks/mdformat
    # TODO: Unpin the version when other plugins add support for mdformat 1.0.0.
    # https://github.com/hukkin/mdformat/issues/555
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: Format Markdown
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
          - mdformat_footnote
