name: Testing

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {torch-version: '2.7', python-version: '3.10'}
          - {torch-version: '2.7', python-version: '3.13'}
          - {torch-version: '2.9', python-version: '3.10'}
          - {torch-version: '2.9', python-version: '3.13'}
          - {torch-version: 'nightly', python-version: '3.10'}
          - {torch-version: 'nightly', python-version: '3.13'}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 40

      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            docs/**
            examples/**
            README.md
            CHANGELOG.md
            .github/workflows/changelog.yml
            .github/workflows/dependabot-auto-merge.yml
            .github/workflows/documentation.yml
            .github/workflows/labeler.yml
            .github/workflows/linting.yml
            .github/workflows/release.yml

      - name: Setup packages
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}
          cuda-version: cpu

      - name: Install main package
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          pip install -e .[full,test]
          pip list

      - name: Run tests
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
